apiVersion: apps/v1
kind: Deployment
metadata:
  name: lr-backend
spec:
  replicas: {{.Values.backend.replicaCount}}}
  selector:
    matchLabels:
      app: lr-backend
  template:
    metadata:
      labels:
        app: lr-backend
    spec:
      containers:
        - name: lr-backend
          image: {{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{.Values.backend.service.port}}}