apiVersion: v1
kind: Service
metadata:
  name: lr-frontend
spec:
  selector:
    app: lr-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{.Values.frontend.service.port}}
  type: ClusterIP