FROM nginx:alpine

COPY pages/home/index.html /usr/share/nginx/html/index.html

COPY pages /usr/share/nginx/html
COPY styles /usr/share/nginx/html/styles
COPY assets /usr/share/nginx/html/assets
COPY js /usr/share/nginx/html/js